services:
  backend:
    image: ghcr.io/dallss/rentapart:latest
    container_name: rentapart-backend
    ports:
      - "8000:8000"
    restart: unless-stopped
  frontend:
    image: ghcr.io/dallss/rent-apart:latest
    container_name: rentapart-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
