name: deploy
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: deploy
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull latest images
        run: |
          docker pull ghcr.io/Dallss/rentapart:latest
          docker pull ghcr.io/Dallss/rentapart-frontend:latest

      - name: Run docker compose
        run: |
          docker compose up -d
